name: magic-nugger-dev

services:
  magic-nugger-postgres:
    extends:
      file: docker-compose.yml
      service: magic-nugger-postgres
    container_name: magic-nugger-postgres-dev

  magic-nugger-web-server:
    extends:
      file: docker-compose.yml
      service: magic-nugger-web-server
    container_name: magic-nugger-web-server-dev
    build:
      target: dev
    volumes:
      - ./web-server:/magic-nugger
      - /magic-nugger/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      ENVIRONMENT: local

volumes:
  postgres_data:
    name: magic-nugger-postgres-data-dev
