import { useState } from "react";
import * as DialogPrimitive from "@radix-ui/react-dialog";
import { DialogOverlay, DialogPortal } from "@/components/ui/dialog";
import { Typography } from "@/components/ui/typography";
import { CartoonButton } from "@/components/ui/cartoon-button";
import { CartoonInput } from "@/components/ui/cartoon-input";
import { RequestSaveQuestionsSchema } from "@magic-nugger-app/shared";
import type { QuestionsFormValues } from "@/feature/room/components/questions-form";
import { toastInfo } from "@/lib/toast";

const PROMPT_TEMPLATE = (levelType: string, amount: string) => `
<task>
Generate quiz questions as a JSON array. Return ONLY the raw JSON array — no markdown, no code fences, no explanation.
</task>

Each question must follow this exact shape:
<schema>
{
  "question": "string",
  "choices": [
    { "text": "string", "is_correct": boolean },
    { "text": "string", "is_correct": boolean},
    { "text": "string", "is_correct": boolean},
    { "text": "string", "is_correct": boolean}
  ]
}
</schema>

<guidelines>
Rules:
- Exactly 4 choices per question
- Exactly 1 choice with is_correct: true
- Questions must be appropriate for level: ${levelType || "<your level type>"}
- Generate exactly ${amount || "<amount>"} questions

Return only the JSON array.
</guidelines>
`;

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSave: (questions: QuestionsFormValues) => Promise<boolean>;
  saving: boolean;
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  onSave,
  saving,
}: AutoGenerateDialogProps) {
  const [levelType, setLevelType] = useState("");
  const [amount, setAmount] = useState("");
  const [output, setOutput] = useState("");
  const [parseError, setParseError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(PROMPT_TEMPLATE(levelType, amount));
    setCopied(true);
    toastInfo("Prompt copied");
    setTimeout(() => setCopied(false), 1500);
  };

  const handleSave = async () => {
    setParseError(null);
    let parsed: unknown;
    try {
      parsed = JSON.parse(output);
    } catch {
      setParseError("Invalid JSON — check the output from your LLM.");
      return;
    }
    const result = RequestSaveQuestionsSchema.safeParse({ questions: parsed });
    if (!result.success) {
      setParseError(
        result.error.errors[0]?.message ?? "Schema validation failed.",
      );
      return;
    }
    const success = await onSave({ questions: result.data.questions });
    if (success) {
      setLevelType("");
      setAmount("");
      setOutput("");
      setParseError(null);
      onOpenChange(false);
    }
  };

  return (
    <DialogPrimitive.Root open={open} onOpenChange={onOpenChange}>
      <DialogPortal>
        <DialogOverlay className="bg-ink/50 backdrop-blur-sm" />
        <DialogPrimitive.Content className="fixed left-1/2 top-1/2 z-50 w-full max-w-lg -translate-x-1/2 -translate-y-1/2 bg-paper border-[3px] border-border rounded-xl shadow-cartoon-lg p-8 flex flex-col gap-6 focus:outline-none">
          <div className="flex flex-col gap-1">
            <DialogPrimitive.Title asChild>
              <Typography variant="subheading">
                Auto generate questions
              </Typography>
            </DialogPrimitive.Title>
            <DialogPrimitive.Description asChild>
              <Typography variant="caption" className="text-ink-soft">
                Enter a topic or level, copy the prompt into your LLM, then
                paste the result below.
              </Typography>
            </DialogPrimitive.Description>
          </div>

          <div className="flex flex-col gap-4">
            <div className="flex gap-3">
              <div className="flex flex-col gap-2 flex-1">
                <Typography variant="label">Topic / Level</Typography>
                <CartoonInput
                  placeholder="e.g. Grade 1 math, Names of cheese..."
                  value={levelType}
                  onChange={(e) => setLevelType(e.target.value)}
                />
              </div>
              <div className="flex flex-col gap-2 w-24">
                <Typography variant="label">Amount</Typography>
                <CartoonInput
                  type="number"
                  min={1}
                  placeholder="10"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                />
              </div>
            </div>
            <CartoonButton
              variant="secondary"
              size="sm"
              onClick={handleCopy}
              className="self-start"
            >
              {copied ? "Copied!" : "Copy prompt"}
            </CartoonButton>
          </div>

          <div className="flex items-center gap-4">
            <span className="flex-1 h-[3px] bg-ink-soft rounded-sm" />
            <Typography variant="label" as="span">
              Paste output
            </Typography>
            <span className="flex-1 h-[3px] bg-ink-soft rounded-sm" />
          </div>

          <div className="flex flex-col gap-3">
            <textarea
              rows={8}
              placeholder='[{"question": "...", "choices": [...]}]'
              value={output}
              onChange={(e) => {
                setOutput(e.target.value);
                setParseError(null);
              }}
              className="w-full rounded-lg border-border border-[3px] px-4 py-3 font-mono min-h-[80px] resize-y focus:outline-none shadow-cartoon-sm"
            />
            {parseError && (
              <Typography variant="error" className="text-red-500">
                {parseError}
              </Typography>
            )}
          </div>

          <CartoonButton
            onClick={handleSave}
            disabled={!output.trim() || saving}
            className="w-full"
            size="sm"
          >
            {saving ? "Saving..." : "Save questions"}
          </CartoonButton>
        </DialogPrimitive.Content>
      </DialogPortal>
    </DialogPrimitive.Root>
  );
}
